name: Check tck (test!)

on:
  workflow_dispatch:
  
jobs:
  check_billet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        env:
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          EMAIL: ${{ secrets.BREVO_EMAIL }}
        run: python main.py
